# Generated by Django 5.1.1 on 2024-09-12 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('miscelaneas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miscelaneas.localidad'),
        ),
    ]
