# Generated by Django 5.1.1 on 2024-09-12 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('miscelaneas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('destinatario_nombre', models.CharField(max_length=50)),
                ('destinatario_apellido', models.CharField(max_length=50)),
                ('destinatario_telefono', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('entregado', 'Entregado')], max_length=50)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miscelaneas.articulos')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('destinatario_localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miscelaneas.localidad')),
            ],
        ),
    ]
