# Generated by Django 5.1.1 on 2024-09-14 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('camiones', '0001_initial'),
        ('choferes', '0001_initial'),
        ('envios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HojaDeRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('fecha_llegada', models.DateTimeField(blank=True, null=True)),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camiones.camion')),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choferes.chofer')),
                ('envios', models.ManyToManyField(to='envios.envio')),
            ],
        ),
    ]
