# Generated by Django 5.1.1 on 2024-09-14 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_remove_cliente_localidad_cliente_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=6)),
                ('volumen', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='clientes.cliente')),
            ],
        ),
    ]
