# Generated by Django 5.1.1 on 2024-09-14 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miscelaneas', '0002_remove_articulos_cliente'),
        ('pedidos', '0002_alter_pedido_articulo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Articulos',
        ),
    ]
