# Generated by Django 5.1.1 on 2024-09-14 22:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_remove_cliente_localidad_cliente_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('id_numero', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('destinatario_nombre', models.CharField(max_length=255)),
                ('destinatario_direccion', models.CharField(max_length=255)),
                ('destinatario_telefono', models.CharField(max_length=20)),
                ('destinatario_email', models.EmailField(max_length=254)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_transito', 'En tránsito'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='clientes.cliente')),
            ],
        ),
    ]
