# Generated by Django 5.1.1 on 2024-09-19 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0002_alter_envio_destinatario_email'),
        ('miscelaneas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='destinatario_provincia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='miscelaneas.provincia'),
        ),
    ]
