# Generated by Django 5.1.1 on 2024-09-19 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0003_envio_destinatario_provincia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envio',
            name='destinatario_provincia',
        ),
    ]
